version: '3.3'
services:
    nginx:
        image: 'nginx'
        container_name: 'nginx'
        ports: 
          - '8200:80'
        volumes: 
          - './nginx/conf:/etc/nginx:ro'
    database:
        image: 'mongo'
        container_name: 'mongod'
        volumes:
          - ./mongo_volume:/data/db
    server:
        hostname: cinser
        build:
            context: '../'
            dockerfile: 'deploy/Dockerfile'
        container_name: 'cinser'
        environment: 
          - MONGODB_URI=$MONGODB_URI
        ports:
          - '${SERVER_PORT}:8080'
        depends_on:
          - nginx
          - database