version: '3'
services:
    database:
        image: 'mongo'
        container_name: 'mongod'
        volumes:
          - ./mongo_volume:/data/db
    server:
        build:
            context: '../'
            dockerfile: 'deploy/Dockerfile'
        container_name: 'cinser'
        ports:
          - '8080:8080'
        env_file: 
          - '../.server.env'
        depends_on:
          - database