version: '3'
services:
    nginx:
        image: 'nginx'
        container_name: : 'nginx'
        env_file: 
          - '../.server.env'
        ports: 
          - '${NGINX_PORT}:{SERVER_PORT}'
        volumes: 
          - './nginx/conf:/etc/nginx:ro'
    database:
        image: 'mongo'
        container_name: 'mongod'
        volumes:
          - ./mongo_volume:/data/db
    server:
        build:
            context: '../'
            dockerfile: 'deploy/Dockerfile'
        container_name: 'cinser'
        env_file: 
          - '../.server.env'
        ports:
          - '${SERVER_PORT}:8080'
        depends_on:
          - database